### ISSUE TITLE
variable not defined

### ISSUE THREAD

**Issue by biernackip** [rieder/MASC#6]
Hi,

I am getting the following traceback when running `../amuse.sh make_a_star_cluster.py -M 1e4 -type ascii`

`Traceback (most recent call last):
  File "make_a_star_cluster.py", line 337, in <module>
    star_metallicity=metallicity,
  File "make_a_star_cluster.py", line 227, in make_a_star_cluster
    number_of_singles + number_of_primaries,
NameError: global name 'number_of_singles' is not defined`

**Comment by rieder** [comment]
Hi @biernackip,
Thanks for reporting!
Please download the latest version, this should now be fixed.
Please also use "txt" instead of "ascii".
Cheers, Steven
